import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    { name: "Home", href: "/" },
    { name: "Carousels", href: "/carousel" },
    { name: "DropDowns", href: "/dropdown" },
    { name: "Table", href: "/table" },
    { name: "Media", href: "/media" },

    { name: "No found", href: "/not-found" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center gap-5 items-center p-4 bg-gray-100">
          {navLinks.map((link) => (
            <a
              key={link.name}
              href={link.href}
              className="text-blue-500 hover:underline"
            >
              {link.name}
            </a>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}
